# The router() function is an HOF (higher order function) that allows you to reuse the same path prefix & properties across multiple endpoints. This is helpful when your api starts to grow and you want to keep your path operations organized.

# Below are the arguments the router() function can take:
# router(prefix::String; tags::Vector, middleware::Vector, interval::Real)
# tags are used to organize endpoints in the autogenerated docs
# middleware is used to setup router & route-specific middleware
# interval is used to support repeat actions (calling a request handler on a set interval in seconds)

# いい感じに/math/maltiply, /math/divide みたいなのが生やせる

using Oxygen

# Any routes that use this router will be automatically grouped 
# under the 'math' tag in the autogenerated documenation
math = router("/math", tags=["math"])

# You can also assign route specific tags
@get math("/multiply/{a}/{b}", tags=["multiplication"]) function(req, a::Float64, b::Float64)
    return a * b
end

@get math("/divide/{a}/{b}") function(req, a::Float64, b::Float64)
    return a / b
end

serve()